nguage: node_js
node_js:
- 8.9.1
branchs:
  only:
  - master
cache:
  apt: true
  directories:
  - node_modules
install:
- git pull
- rm -f package-lock.json && npm install
script:
- npm run build
after_success:
- chmod 600 ~/.ssh/id_rsa
- rm -rf /var/www/pc/*
- scp -o stricthostkeychecking=no -r ./dist/* /var/www/pc
before_install:
- openssl aes-256-cbc -K $encrypted_9c9e33ab7bb2_key -iv $encrypted_9c9e33ab7bb2_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
